### ISSUE TITLE
Choose document generator system

### ISSUE THREAD

**Issue by phretor** [rfquack/RFQuack#19]
I'm asking to RFQuack's friends to help me choose the doc-generation system. Here are the options I know:

- GitBook
  - PROs: easy to get started with, Markdown based
  - CONs: kinda proprietary

- Docusaurus:
  - PROs: fully open source, Markdown based, simple
  - CONs: none known to me

- MkDocs
  - PROs: Markdown based, active community, many themes
  - CONs: maybe old?

- Sphinx:
  - PROs: well supported, mature product
  - CONs: old, Python centric

**Comment by ResistanceIsUseless** [comment]
I've personally used Hugo and found it pretty straight forward. It's based on Go and uses Go Templating.

**Comment by ResistanceIsUseless** [comment]
Also heard https://astro.build/ is nice.

**Comment by phretor** [comment]
Hugo and Astro are static site generators. I was looking for doc-specific generators.

**Comment by phretor** [comment]
MkDocs is the chosen one.
