### ISSUE TITLE
ECRFv2: Building bug with ECRF set

### ISSUE THREAD

**Issue by AkaBkn** [rfquack/RFQuack#32]
## Describe the bug

**lib/RadioLib/src/Module.h:49**
```Module(RADIOLIB_PIN_TYPE cs, RADIOLIB_PIN_TYPE irq, RADIOLIB_PIN_TYPE rst, RADIOLIB_PIN_TYPE gpio, SPIClass& spi, SPISettings spiSettings = RADIOLIB_DEFAULT_SPI_SETTINGS);```

**docker/project/src/main.cpp.j2**
```
RadioA radioA = new Module(
  {{ RADIOA_CS }},
  {{ RADIOA_IRQ|default('RADIOLIB_NC') }},
  {{ RADIOA_RST|default('RADIOLIB_NC') }}

{% if ECRF is defined %}
  , SPIH, spiSettings
{% endif %}
```

main.cpp.j2 misses the `gpio` argument

## To Reproduce

having build.env:
```
BOARD=ESP32
ECRF=true

RADIOA=CC1101
RADIOA_CS=5
RADIOA_IRQ=2
RADIOA_GP=4

RADIOB=CC1101
RADIOB_CS=27
RADIOB_IRQ=25
RADIOB_GP=26


RADIOC=nRF24
RADIOC_CS=15
RADIOC_CE=33
RADIOC_IRQ=7
```

`make clean build`

## Expected behavior

compiles fine

**Comment by phretor** [comment]
Please check the documentation for the allowed variables. _CE or _GP don't mean much to RFQuack.

**Comment by phretor** [comment]
@AkaBkn please check - it compiles on my side.

**Comment by AkaBkn** [comment]
@phretor looks good, thx :) btw. would be cool to have an example `build.env` for ECRFv2 with nRF24 too

**Comment by phretor** [comment]
I'll test it when I'll receive my ECRFv2

**Comment by joelsernamoreno** [comment]
Mm... Error: Unknown development platform 'espressif32'??

**Comment by phretor** [comment]
> Mm... Error: Unknown development platform 'espressif32'??

Have you tried to change the platform value into platformio.ini ?

**Comment by joelsernamoreno** [comment]
Fix: platformio upgrade --dev

**Comment by gisforgirard** [comment]
not sure why you have RADIOC_.... set, perhaps see https://github.com/joelsernamoreno/EvilCrow-RF for more detailed instructions:

![Screenshot from 2023-02-04 06-35-17](https://user-images.githubusercontent.com/17693551/216765107-9371b04d-bbc1-4946-8169-7e6283dc51ee.png)

**Comment by temskiy** [comment]
I add [PR](https://github.com/rfquack/RFQuack/pull/47) with tested build.env for ECRFv2

**Comment by phretor** [comment]
Awesome. Thanks @temskiy!
