### ISSUE TITLE
Please help with my pinout

### ISSUE THREAD

**Issue by Crsarmv7l** [rfquack/RFQuack#40]
Finally got back to trying to get rfquack working, and after compiling and installing python 3.10.10 on my debian machine, working through the oddities of the build (not using poetry to install depends, only pip with the requirements), etc, my board is flashed and the interactive environment works.
..
   However, I can only access q.dongle... Which means I likely wired something wrong with my cc1101. Its late and this has taken me a while so I can't say I am surprised. I was hoping for another set of eyes to take a look please.

I am using an ebyte cc1101 with this pinout:

![Screenshot 2023-03-23 11 46 22 PM](https://user-images.githubusercontent.com/85343771/227420139-7a8a8b97-af9b-4df5-826d-a6256444eb4d.png)

and I am using a WeMoS Lolin32 with this pinout:

![ESP32-WeMos-LOLIN32-pinout-mischianti (1)](https://user-images.githubusercontent.com/85343771/227420216-03319e41-33d4-40e6-99e8-3f17707e1faf.png)

I connected vcc to 3v, ground to ground, and MISO/MOSI/SCK/and CS to these:

![Screenshot 2023-03-23 11 54 49 PM](https://user-images.githubusercontent.com/85343771/227420480-84d0684e-5465-4ddd-801a-1ef454015869.png)

In build.env RadioA_CS is 34

![Screenshot 2023-03-24 12 03 17 AM](https://user-images.githubusercontent.com/85343771/227421492-ce007fe7-888c-42e6-946a-b12074f778f4.png)

RadioA_IRQ (GD0) is 27

![Screenshot 2023-03-24 12 05 04 AM](https://user-images.githubusercontent.com/85343771/227421700-0420f7b4-f9f4-4654-a0b9-c28e484d622f.png)

Really just hoping I made a silly mistake with the wiring, and it will be a simple rewire, reflash and I can finally give this a go.

Thanks

**Comment by phretor** [comment]
Wiring and configuration look in order. Can you share a dump of the console output at boot, possibly with log/dev/debug enabled?

Define the relevant variables in your build.env - the complete set of build variables can be guessed from here - https://github.com/rfquack/RFQuack/blob/master/docker/project/src/main.cpp.j2

**Comment by Crsarmv7l** [comment]
Well that solved it. Unfortunately. pio device monitor showed it was constantly browning out. It exhibited that behavior even with gpio/cc1101 completely disconnected.

I do have another board, a feather ESP32-S3 with no PSRAM and I have tried building RFquack for that ( with adafruit_feather_esp32s3_nopsram  for board in platformio.ini) but it fails every time with the following:

[build.txt](https://github.com/rfquack/RFQuack/files/11062551/build.txt)

**Comment by Crsarmv7l** [comment]
Picked up an original feather esp32. So I'll close this and hopefully finally be able to get this to work
