### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by Crsarmv7l** [rfquack/RFQuack#42]
I am aware this is scriptable using python and very similar to the Yardstick 1. Can you provide an example script just to make sure I am working with it correctly

**Comment by phretor** [comment]
This is the most complete and working example you'll find: https://github.com/rfquack/RFQuack/tree/master/examples/demos

If you're interested in the recorded demo so you can follow along: https://youtu.be/XGDuEhhK6gQ

**Comment by Crsarmv7l** [comment]
> This is the most complete and working example you'll find: https://github.com/rfquack/RFQuack/tree/master/examples/demos
> 
> If you're interested in the recorded demo so you can follow along: https://youtu.be/XGDuEhhK6gQ

Thank you I will check it out. Being able to write python scripts for the YS1 is why I liked it so much. With the poetry/python env I wasn't sure if that would affect the writing of a python script for rfquack.

Hopefully I can get a better understanding from the demo

**Comment by phretor** [comment]
It's just Python. Pyenv and Poetry are just modern Python dev practice.
